grant all privileges on *.* to 'saleel'@'%' ;
grant all privileges on dac1.* to 'dac1'@'%';
grant all privileges on dac2.* to 'dac2'@'%';
grant all privileges on dac3.* to 'dac3'@'%';
grant all privileges on dac4.* to 'dac4'@'%';
grant all privileges on dac5.* to 'dac5'@'%';
grant all privileges on dac6.* to 'dac6'@'%';
grant all privileges on dac7.* to 'dac7'@'%';
grant all privileges on dac8.* to 'dac8'@'%';
grant all privileges on dac9.* to 'dac9'@'%';
grant all privileges on dac10.* to 'dac10'@'%' ;
grant all privileges on dac11.* to 'dac11'@'%' ;
grant all privileges on dac12.* to 'dac12'@'%' ;
grant all privileges on dac13.* to 'dac13'@'%' ;
grant all privileges on dac14.* to 'dac14'@'%' ;
grant all privileges on dac15.* to 'dac15'@'%' ;
grant all privileges on dac16.* to 'dac16'@'%' ;
grant all privileges on dac17.* to 'dac17'@'%' ;
grant all privileges on dac18.* to 'dac18'@'%' ;
grant all privileges on dac19.* to 'dac19'@'%' ;
grant all privileges on dac20.* to 'dac20'@'%' ;
grant all privileges on dac21.* to 'dac21'@'%' ;
grant all privileges on dac22.* to 'dac22'@'%' ;
grant all privileges on dac23.* to 'dac23'@'%' ;
grant all privileges on dac24.* to 'dac24'@'%' ;
grant all privileges on dac25.* to 'dac25'@'%' ;
grant all privileges on dac26.* to 'dac26'@'%' ;
grant all privileges on dac27.* to 'dac27'@'%' ;
grant all privileges on dac28.* to 'dac28'@'%' ;
grant all privileges on dac29.* to 'dac29'@'%' ;
grant all privileges on dac30.* to 'dac30'@'%' ;
grant all privileges on dac31.* to 'dac31'@'%' ;
grant all privileges on dac32.* to 'dac32'@'%' ;
grant all privileges on dac33.* to 'dac33'@'%' ;
grant all privileges on dac34.* to 'dac34'@'%' ;
grant all privileges on dac35.* to 'dac35'@'%' ;
grant all privileges on dac36.* to 'dac36'@'%' ;
grant all privileges on dac37.* to 'dac37'@'%' ;
grant all privileges on dac38.* to 'dac38'@'%' ;
grant all privileges on dac39.* to 'dac39'@'%' ;
grant all privileges on dac40.* to 'dac40'@'%' ;
grant all privileges on dac41.* to 'dac41'@'%' ;
grant all privileges on dac42.* to 'dac42'@'%' ;
grant all privileges on dac43.* to 'dac43'@'%' ;
grant all privileges on dac44.* to 'dac44'@'%' ;
grant all privileges on dac45.* to 'dac45'@'%' ;
grant all privileges on dac46.* to 'dac46'@'%' ;
grant all privileges on dac47.* to 'dac47'@'%' ;
grant all privileges on dac48.* to 'dac48'@'%' ;
grant all privileges on dac49.* to 'dac49'@'%' ;
grant all privileges on dac50.* to 'dac50'@'%' ;
											   
											   
grant all privileges on dac51.* to 'dac51'@'%' ;
grant all privileges on dac52.* to 'dac52'@'%' ;
grant all privileges on dac53.* to 'dac53'@'%' ;
grant all privileges on dac54.* to 'dac54'@'%' ;
grant all privileges on dac55.* to 'dac55'@'%' ;
grant all privileges on dac56.* to 'dac56'@'%' ;
grant all privileges on dac57.* to 'dac57'@'%' ;
grant all privileges on dac58.* to 'dac58'@'%' ;
grant all privileges on dac59.* to 'dac59'@'%' ;
grant all privileges on dac60.* to 'dac60'@'%' ;
grant all privileges on dac61.* to 'dac61'@'%' ;
grant all privileges on dac62.* to 'dac62'@'%' ;
grant all privileges on dac63.* to 'dac63'@'%' ;
grant all privileges on dac64.* to 'dac64'@'%' ;
grant all privileges on dac65.* to 'dac65'@'%' ;
grant all privileges on dac66.* to 'dac66'@'%' ;
grant all privileges on dac67.* to 'dac67'@'%' ;
grant all privileges on dac68.* to 'dac68'@'%' ;
grant all privileges on dac69.* to 'dac69'@'%' ;
grant all privileges on dac70.* to 'dac70'@'%' ;
grant all privileges on dac71.* to 'dac71'@'%' ;
grant all privileges on dac72.* to 'dac72'@'%' ;
grant all privileges on dac73.* to 'dac73'@'%' ;
grant all privileges on dac74.* to 'dac74'@'%' ;
grant all privileges on dac75.* to 'dac75'@'%' ;
grant all privileges on dac76.* to 'dac76'@'%' ;
grant all privileges on dac77.* to 'dac77'@'%' ;
grant all privileges on dac78.* to 'dac78'@'%' ;
grant all privileges on dac79.* to 'dac79'@'%' ;
grant all privileges on dac80.* to 'dac80'@'%' ;
grant all privileges on dac81.* to 'dac81'@'%' ;
grant all privileges on dac82.* to 'dac82'@'%' ;
grant all privileges on dac83.* to 'dac83'@'%' ;
grant all privileges on dac84.* to 'dac84'@'%' ;
grant all privileges on dac85.* to 'dac85'@'%' ;
grant all privileges on dac86.* to 'dac86'@'%' ;
grant all privileges on dac87.* to 'dac87'@'%' ;
grant all privileges on dac88.* to 'dac88'@'%' ;
grant all privileges on dac89.* to 'dac89'@'%' ;
grant all privileges on dac90.* to 'dac90'@'%' ;
grant all privileges on dac91.* to 'dac91'@'%' ;
grant all privileges on dac92.* to 'dac92'@'%' ;
grant all privileges on dac93.* to 'dac93'@'%' ;
grant all privileges on dac94.* to 'dac94'@'%' ;
grant all privileges on dac95.* to 'dac95'@'%' ;
grant all privileges on dac96.* to 'dac96'@'%' ;
grant all privileges on dac97.* to 'dac97'@'%' ;
grant all privileges on dac98.* to 'dac98'@'%' ;
grant all privileges on dac99.* to 'dac99'@'%' ;
grant all privileges on dac100.* to 'dac100'@'%' ;
												
grant all privileges on dac101.* to 'dac101'@'%' ;
grant all privileges on dac102.* to 'dac102'@'%' ;
grant all privileges on dac103.* to 'dac103'@'%' ;
grant all privileges on dac104.* to 'dac104'@'%' ;
grant all privileges on dac105.* to 'dac105'@'%' ;
grant all privileges on dac106.* to 'dac106'@'%' ;
grant all privileges on dac107.* to 'dac107'@'%' ;
grant all privileges on dac108.* to 'dac108'@'%' ;
grant all privileges on dac109.* to 'dac109'@'%' ;
grant all privileges on dac110.* to 'dac110'@'%' ;
grant all privileges on dac111.* to 'dac111'@'%' ;
grant all privileges on dac112.* to 'dac112'@'%' ;
grant all privileges on dac113.* to 'dac113'@'%' ;
grant all privileges on dac114.* to 'dac114'@'%' ;
grant all privileges on dac115.* to 'dac115'@'%' ;
grant all privileges on dac116.* to 'dac116'@'%' ;
grant all privileges on dac117.* to 'dac117'@'%' ;
grant all privileges on dac118.* to 'dac118'@'%' ;
grant all privileges on dac119.* to 'dac119'@'%' ;
grant all privileges on dac120.* to 'dac120'@'%' ;